### ISSUE TITLE
docker-compose: peermanager crashes after X seconds

### ISSUE THREAD

**Issue by Pitastic** [coinbase/toshi#245]
After building the docker image from the git repo and creating the posgresql db I am able to start the whole bunch of containers (via docker-compose).

The service is up and running, reachable on port 5000 and synching is in progress.

But after 10 to 60 seconds the container for the peermanager with

```
/usr/local/bundle/bundler/gems/bitcoin-ruby-69123208d45a/lib/bitcoin/protocol.rb:62: unpack_var_string': undefined method > for nil:NilClass (NoMethodError)'
```

As it turns out this error is throwing if you try to use int-comparefunctions on a non int object.

It works if the `size` variable in line 62 is converted to string and back to int (to make sure it is int).
The easiest way for me was to workaround with a `sed` search and replace statement for this line in the `docker-compose.yml`  (I edit the `command:` statement only): 

```
peermanager:
  <<: *web
  ports: []
  command: sh -c "bundle exec find /usr/local/bundle -type f -iname protocol.rb -exec sed -i '/size > 0 ? (string, payload = payload.unpack(/s/size/size.to_s.to_i/g' {} \; && ruby bin/peer_manager.rb"
```

Hope this helps others...
